# 通过Dockerfile的方式构建spring cloud镜像
# spring cloud对应jar包文件地址https://gitee.com/brnokerzenlicht/springclouddemo/raw/f_docker/server1/src/main/resources/server1-1.0-SNAPSHOT.jar
FROM java:8
VOLUME /tmp
ADD server1-1.0-SNAPSHOT.jar app.jar
EXPOSE 8761
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
